#!/usr/bin/env bash
set -e

check_install () {
	echo -n "checking if $1 is installed... "
	if command -v $1 &> /dev/null ; then
		echo "✓"
	else
		echo "✗"
		return 1
	fi
}

check_install git
check_install nvim
check_install tmux
check_install atuin
check_install ghostty

# oh-my-zsh
if [ ! -d ~/.oh-my-zsh ]; then
	echo "oh-my-zsh not found. installing..."
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
if [ ! -f ~/.zshrc ]; then
	ln -s ${PWD}/zsh/zshrc ~/.zshrc
fi

# neovim
if [ ! -d ~/.config/nvim ]; then
	ln -s ${PWD}/nvim ~/.config/nvim
fi

# tmux
if [ ! -d ~/.tmux/plugins/tpm ]; then
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
if [ ! -d ~/.config/tmux ]; then
	ln -s ${PWD}/tmux ~/.config/tmux
	echo "don't forget to disable the default ctrl-space binding in MacOS so you can use it as the tmux prefix"
	echo "System Settings > Keyboard shortcuts > Input Sources - uncheck all"
fi

# ghostty
if [ ! -d ~/.config/ghostty ]; then
	ln -s ${PWD}/ghostty ~/.config/ghostty
fi
