#!/usr/bin/env bash
set -e

check_install () {
	echo -n "checking if $1 is installed... "
	if command -v $1 &> /dev/null ; then
		echo "✓"
	else
		echo "✗"
		return 1
	fi
}

check_install git

# neovim
check_install nvim
if [ ! -d ~/.config/nvim ]; then
	ln -s ${PWD}/nvim ~/.config/nvim
fi

# tmux
check_install tmux
if [ ! -d ~/.tmux/plugins/tpm ]; then
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
if [ ! -d ~/.config/tmux ]; then
	ln -s ${PWD}/tmux ~/.config/tmux
fi

