# attach to tmux session if not already in tmux and in interactive shell
if [[ -z "$TMUX" ]] && [[ -n "$PS1" ]]; then
    tmux attach-session -t tmux || tmux new-session -s tmux
fi

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

export VISUAL=nvim
export EDITOR=nvim

ZSH_THEME="kphoen"
HYPHEN_INSENSITIVE="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias zshconfig="nvim ~/.zshrc"
alias zshreset="source ~/.zshrc"

# atuin
. "$HOME/.atuin/bin/env"
eval "$(atuin init zsh)"

# add go bin to PATH
export PATH=$HOME/go/bin:$PATH

# add ~/tools to PATH
export PATH=$PATH:$HOME/tools

export TERM=tmux-256color

# go
export PATH="$PATH:/Users/julia/go/bin"

# rust
. "$HOME/.cargo/env"

alias ls='eza --color=always --group-directories-first --icons --oneline'

cd $HOME
fastfetch
