# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="refined"
HYPHEN_INSENSITIVE="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias zshconfig="nvim ~/.zshrc"
alias zshreset="source ~/.zshrc"

# atuin
. "$HOME/.atuin/bin/env"
eval "$(atuin init zsh)"

# add go bin to PATH
export PATH=$HOME/go/bin:$PATH

# add ~/tools to PATH
export PATH=$PATH:$HOME/tools

export TERM=tmux-256color
